// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cv.proto

package ru.itis.hr.grpc.pb.cv;

public final class Cv {
  private Cv() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CVRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CVRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated string skills = 1;</code>
     * @return A list containing the skills.
     */
    java.util.List<java.lang.String>
        getSkillsList();
    /**
     * <code>repeated string skills = 1;</code>
     * @return The count of skills.
     */
    int getSkillsCount();
    /**
     * <code>repeated string skills = 1;</code>
     * @param index The index of the element to return.
     * @return The skills at the given index.
     */
    java.lang.String getSkills(int index);
    /**
     * <code>repeated string skills = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the skills at the given index.
     */
    com.google.protobuf.ByteString
        getSkillsBytes(int index);
  }
  /**
   * Protobuf type {@code CVRequest}
   */
  public static final class CVRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:CVRequest)
      CVRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CVRequest.newBuilder() to construct.
    private CVRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CVRequest() {
      skills_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new CVRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CVRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                skills_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              skills_.add(s);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          skills_ = skills_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ru.itis.hr.grpc.pb.cv.Cv.internal_static_CVRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ru.itis.hr.grpc.pb.cv.Cv.internal_static_CVRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ru.itis.hr.grpc.pb.cv.Cv.CVRequest.class, ru.itis.hr.grpc.pb.cv.Cv.CVRequest.Builder.class);
    }

    public static final int SKILLS_FIELD_NUMBER = 1;
    private com.google.protobuf.LazyStringList skills_;
    /**
     * <code>repeated string skills = 1;</code>
     * @return A list containing the skills.
     */
    public com.google.protobuf.ProtocolStringList
        getSkillsList() {
      return skills_;
    }
    /**
     * <code>repeated string skills = 1;</code>
     * @return The count of skills.
     */
    public int getSkillsCount() {
      return skills_.size();
    }
    /**
     * <code>repeated string skills = 1;</code>
     * @param index The index of the element to return.
     * @return The skills at the given index.
     */
    public java.lang.String getSkills(int index) {
      return skills_.get(index);
    }
    /**
     * <code>repeated string skills = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the skills at the given index.
     */
    public com.google.protobuf.ByteString
        getSkillsBytes(int index) {
      return skills_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < skills_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, skills_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < skills_.size(); i++) {
          dataSize += computeStringSizeNoTag(skills_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getSkillsList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ru.itis.hr.grpc.pb.cv.Cv.CVRequest)) {
        return super.equals(obj);
      }
      ru.itis.hr.grpc.pb.cv.Cv.CVRequest other = (ru.itis.hr.grpc.pb.cv.Cv.CVRequest) obj;

      if (!getSkillsList()
          .equals(other.getSkillsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getSkillsCount() > 0) {
        hash = (37 * hash) + SKILLS_FIELD_NUMBER;
        hash = (53 * hash) + getSkillsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ru.itis.hr.grpc.pb.cv.Cv.CVRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.itis.hr.grpc.pb.cv.Cv.CVRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.itis.hr.grpc.pb.cv.Cv.CVRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.itis.hr.grpc.pb.cv.Cv.CVRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.itis.hr.grpc.pb.cv.Cv.CVRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.itis.hr.grpc.pb.cv.Cv.CVRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.itis.hr.grpc.pb.cv.Cv.CVRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ru.itis.hr.grpc.pb.cv.Cv.CVRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ru.itis.hr.grpc.pb.cv.Cv.CVRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ru.itis.hr.grpc.pb.cv.Cv.CVRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ru.itis.hr.grpc.pb.cv.Cv.CVRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ru.itis.hr.grpc.pb.cv.Cv.CVRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ru.itis.hr.grpc.pb.cv.Cv.CVRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CVRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CVRequest)
        ru.itis.hr.grpc.pb.cv.Cv.CVRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ru.itis.hr.grpc.pb.cv.Cv.internal_static_CVRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ru.itis.hr.grpc.pb.cv.Cv.internal_static_CVRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ru.itis.hr.grpc.pb.cv.Cv.CVRequest.class, ru.itis.hr.grpc.pb.cv.Cv.CVRequest.Builder.class);
      }

      // Construct using ru.itis.hr.grpc.pb.cv.Cv.CVRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        skills_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ru.itis.hr.grpc.pb.cv.Cv.internal_static_CVRequest_descriptor;
      }

      @java.lang.Override
      public ru.itis.hr.grpc.pb.cv.Cv.CVRequest getDefaultInstanceForType() {
        return ru.itis.hr.grpc.pb.cv.Cv.CVRequest.getDefaultInstance();
      }

      @java.lang.Override
      public ru.itis.hr.grpc.pb.cv.Cv.CVRequest build() {
        ru.itis.hr.grpc.pb.cv.Cv.CVRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ru.itis.hr.grpc.pb.cv.Cv.CVRequest buildPartial() {
        ru.itis.hr.grpc.pb.cv.Cv.CVRequest result = new ru.itis.hr.grpc.pb.cv.Cv.CVRequest(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) != 0)) {
          skills_ = skills_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.skills_ = skills_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ru.itis.hr.grpc.pb.cv.Cv.CVRequest) {
          return mergeFrom((ru.itis.hr.grpc.pb.cv.Cv.CVRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ru.itis.hr.grpc.pb.cv.Cv.CVRequest other) {
        if (other == ru.itis.hr.grpc.pb.cv.Cv.CVRequest.getDefaultInstance()) return this;
        if (!other.skills_.isEmpty()) {
          if (skills_.isEmpty()) {
            skills_ = other.skills_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureSkillsIsMutable();
            skills_.addAll(other.skills_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ru.itis.hr.grpc.pb.cv.Cv.CVRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ru.itis.hr.grpc.pb.cv.Cv.CVRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.LazyStringList skills_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureSkillsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          skills_ = new com.google.protobuf.LazyStringArrayList(skills_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated string skills = 1;</code>
       * @return A list containing the skills.
       */
      public com.google.protobuf.ProtocolStringList
          getSkillsList() {
        return skills_.getUnmodifiableView();
      }
      /**
       * <code>repeated string skills = 1;</code>
       * @return The count of skills.
       */
      public int getSkillsCount() {
        return skills_.size();
      }
      /**
       * <code>repeated string skills = 1;</code>
       * @param index The index of the element to return.
       * @return The skills at the given index.
       */
      public java.lang.String getSkills(int index) {
        return skills_.get(index);
      }
      /**
       * <code>repeated string skills = 1;</code>
       * @param index The index of the value to return.
       * @return The bytes of the skills at the given index.
       */
      public com.google.protobuf.ByteString
          getSkillsBytes(int index) {
        return skills_.getByteString(index);
      }
      /**
       * <code>repeated string skills = 1;</code>
       * @param index The index to set the value at.
       * @param value The skills to set.
       * @return This builder for chaining.
       */
      public Builder setSkills(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureSkillsIsMutable();
        skills_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string skills = 1;</code>
       * @param value The skills to add.
       * @return This builder for chaining.
       */
      public Builder addSkills(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureSkillsIsMutable();
        skills_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string skills = 1;</code>
       * @param values The skills to add.
       * @return This builder for chaining.
       */
      public Builder addAllSkills(
          java.lang.Iterable<java.lang.String> values) {
        ensureSkillsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, skills_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string skills = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSkills() {
        skills_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string skills = 1;</code>
       * @param value The bytes of the skills to add.
       * @return This builder for chaining.
       */
      public Builder addSkillsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureSkillsIsMutable();
        skills_.add(value);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:CVRequest)
    }

    // @@protoc_insertion_point(class_scope:CVRequest)
    private static final ru.itis.hr.grpc.pb.cv.Cv.CVRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ru.itis.hr.grpc.pb.cv.Cv.CVRequest();
    }

    public static ru.itis.hr.grpc.pb.cv.Cv.CVRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CVRequest>
        PARSER = new com.google.protobuf.AbstractParser<CVRequest>() {
      @java.lang.Override
      public CVRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CVRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CVRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CVRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ru.itis.hr.grpc.pb.cv.Cv.CVRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CVOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CV)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string candidateName = 1;</code>
     * @return The candidateName.
     */
    java.lang.String getCandidateName();
    /**
     * <code>string candidateName = 1;</code>
     * @return The bytes for candidateName.
     */
    com.google.protobuf.ByteString
        getCandidateNameBytes();

    /**
     * <code>uint32 candidateAge = 2;</code>
     * @return The candidateAge.
     */
    int getCandidateAge();

    /**
     * <code>uint32 experience = 3;</code>
     * @return The experience.
     */
    int getExperience();

    /**
     * <code>repeated string skills = 4;</code>
     * @return A list containing the skills.
     */
    java.util.List<java.lang.String>
        getSkillsList();
    /**
     * <code>repeated string skills = 4;</code>
     * @return The count of skills.
     */
    int getSkillsCount();
    /**
     * <code>repeated string skills = 4;</code>
     * @param index The index of the element to return.
     * @return The skills at the given index.
     */
    java.lang.String getSkills(int index);
    /**
     * <code>repeated string skills = 4;</code>
     * @param index The index of the value to return.
     * @return The bytes of the skills at the given index.
     */
    com.google.protobuf.ByteString
        getSkillsBytes(int index);

    /**
     * <code>string experienceDescription = 5;</code>
     * @return The experienceDescription.
     */
    java.lang.String getExperienceDescription();
    /**
     * <code>string experienceDescription = 5;</code>
     * @return The bytes for experienceDescription.
     */
    com.google.protobuf.ByteString
        getExperienceDescriptionBytes();
  }
  /**
   * Protobuf type {@code CV}
   */
  public static final class CV extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:CV)
      CVOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CV.newBuilder() to construct.
    private CV(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CV() {
      candidateName_ = "";
      skills_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      experienceDescription_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new CV();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CV(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              candidateName_ = s;
              break;
            }
            case 16: {

              candidateAge_ = input.readUInt32();
              break;
            }
            case 24: {

              experience_ = input.readUInt32();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                skills_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              skills_.add(s);
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              experienceDescription_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          skills_ = skills_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ru.itis.hr.grpc.pb.cv.Cv.internal_static_CV_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ru.itis.hr.grpc.pb.cv.Cv.internal_static_CV_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ru.itis.hr.grpc.pb.cv.Cv.CV.class, ru.itis.hr.grpc.pb.cv.Cv.CV.Builder.class);
    }

    public static final int CANDIDATENAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object candidateName_;
    /**
     * <code>string candidateName = 1;</code>
     * @return The candidateName.
     */
    @java.lang.Override
    public java.lang.String getCandidateName() {
      java.lang.Object ref = candidateName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        candidateName_ = s;
        return s;
      }
    }
    /**
     * <code>string candidateName = 1;</code>
     * @return The bytes for candidateName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCandidateNameBytes() {
      java.lang.Object ref = candidateName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        candidateName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CANDIDATEAGE_FIELD_NUMBER = 2;
    private int candidateAge_;
    /**
     * <code>uint32 candidateAge = 2;</code>
     * @return The candidateAge.
     */
    @java.lang.Override
    public int getCandidateAge() {
      return candidateAge_;
    }

    public static final int EXPERIENCE_FIELD_NUMBER = 3;
    private int experience_;
    /**
     * <code>uint32 experience = 3;</code>
     * @return The experience.
     */
    @java.lang.Override
    public int getExperience() {
      return experience_;
    }

    public static final int SKILLS_FIELD_NUMBER = 4;
    private com.google.protobuf.LazyStringList skills_;
    /**
     * <code>repeated string skills = 4;</code>
     * @return A list containing the skills.
     */
    public com.google.protobuf.ProtocolStringList
        getSkillsList() {
      return skills_;
    }
    /**
     * <code>repeated string skills = 4;</code>
     * @return The count of skills.
     */
    public int getSkillsCount() {
      return skills_.size();
    }
    /**
     * <code>repeated string skills = 4;</code>
     * @param index The index of the element to return.
     * @return The skills at the given index.
     */
    public java.lang.String getSkills(int index) {
      return skills_.get(index);
    }
    /**
     * <code>repeated string skills = 4;</code>
     * @param index The index of the value to return.
     * @return The bytes of the skills at the given index.
     */
    public com.google.protobuf.ByteString
        getSkillsBytes(int index) {
      return skills_.getByteString(index);
    }

    public static final int EXPERIENCEDESCRIPTION_FIELD_NUMBER = 5;
    private volatile java.lang.Object experienceDescription_;
    /**
     * <code>string experienceDescription = 5;</code>
     * @return The experienceDescription.
     */
    @java.lang.Override
    public java.lang.String getExperienceDescription() {
      java.lang.Object ref = experienceDescription_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        experienceDescription_ = s;
        return s;
      }
    }
    /**
     * <code>string experienceDescription = 5;</code>
     * @return The bytes for experienceDescription.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getExperienceDescriptionBytes() {
      java.lang.Object ref = experienceDescription_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        experienceDescription_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getCandidateNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, candidateName_);
      }
      if (candidateAge_ != 0) {
        output.writeUInt32(2, candidateAge_);
      }
      if (experience_ != 0) {
        output.writeUInt32(3, experience_);
      }
      for (int i = 0; i < skills_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, skills_.getRaw(i));
      }
      if (!getExperienceDescriptionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, experienceDescription_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getCandidateNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, candidateName_);
      }
      if (candidateAge_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, candidateAge_);
      }
      if (experience_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, experience_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < skills_.size(); i++) {
          dataSize += computeStringSizeNoTag(skills_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getSkillsList().size();
      }
      if (!getExperienceDescriptionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, experienceDescription_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ru.itis.hr.grpc.pb.cv.Cv.CV)) {
        return super.equals(obj);
      }
      ru.itis.hr.grpc.pb.cv.Cv.CV other = (ru.itis.hr.grpc.pb.cv.Cv.CV) obj;

      if (!getCandidateName()
          .equals(other.getCandidateName())) return false;
      if (getCandidateAge()
          != other.getCandidateAge()) return false;
      if (getExperience()
          != other.getExperience()) return false;
      if (!getSkillsList()
          .equals(other.getSkillsList())) return false;
      if (!getExperienceDescription()
          .equals(other.getExperienceDescription())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CANDIDATENAME_FIELD_NUMBER;
      hash = (53 * hash) + getCandidateName().hashCode();
      hash = (37 * hash) + CANDIDATEAGE_FIELD_NUMBER;
      hash = (53 * hash) + getCandidateAge();
      hash = (37 * hash) + EXPERIENCE_FIELD_NUMBER;
      hash = (53 * hash) + getExperience();
      if (getSkillsCount() > 0) {
        hash = (37 * hash) + SKILLS_FIELD_NUMBER;
        hash = (53 * hash) + getSkillsList().hashCode();
      }
      hash = (37 * hash) + EXPERIENCEDESCRIPTION_FIELD_NUMBER;
      hash = (53 * hash) + getExperienceDescription().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ru.itis.hr.grpc.pb.cv.Cv.CV parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.itis.hr.grpc.pb.cv.Cv.CV parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.itis.hr.grpc.pb.cv.Cv.CV parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.itis.hr.grpc.pb.cv.Cv.CV parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.itis.hr.grpc.pb.cv.Cv.CV parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.itis.hr.grpc.pb.cv.Cv.CV parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.itis.hr.grpc.pb.cv.Cv.CV parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ru.itis.hr.grpc.pb.cv.Cv.CV parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ru.itis.hr.grpc.pb.cv.Cv.CV parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ru.itis.hr.grpc.pb.cv.Cv.CV parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ru.itis.hr.grpc.pb.cv.Cv.CV parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ru.itis.hr.grpc.pb.cv.Cv.CV parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ru.itis.hr.grpc.pb.cv.Cv.CV prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CV}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CV)
        ru.itis.hr.grpc.pb.cv.Cv.CVOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ru.itis.hr.grpc.pb.cv.Cv.internal_static_CV_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ru.itis.hr.grpc.pb.cv.Cv.internal_static_CV_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ru.itis.hr.grpc.pb.cv.Cv.CV.class, ru.itis.hr.grpc.pb.cv.Cv.CV.Builder.class);
      }

      // Construct using ru.itis.hr.grpc.pb.cv.Cv.CV.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        candidateName_ = "";

        candidateAge_ = 0;

        experience_ = 0;

        skills_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        experienceDescription_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ru.itis.hr.grpc.pb.cv.Cv.internal_static_CV_descriptor;
      }

      @java.lang.Override
      public ru.itis.hr.grpc.pb.cv.Cv.CV getDefaultInstanceForType() {
        return ru.itis.hr.grpc.pb.cv.Cv.CV.getDefaultInstance();
      }

      @java.lang.Override
      public ru.itis.hr.grpc.pb.cv.Cv.CV build() {
        ru.itis.hr.grpc.pb.cv.Cv.CV result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ru.itis.hr.grpc.pb.cv.Cv.CV buildPartial() {
        ru.itis.hr.grpc.pb.cv.Cv.CV result = new ru.itis.hr.grpc.pb.cv.Cv.CV(this);
        int from_bitField0_ = bitField0_;
        result.candidateName_ = candidateName_;
        result.candidateAge_ = candidateAge_;
        result.experience_ = experience_;
        if (((bitField0_ & 0x00000001) != 0)) {
          skills_ = skills_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.skills_ = skills_;
        result.experienceDescription_ = experienceDescription_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ru.itis.hr.grpc.pb.cv.Cv.CV) {
          return mergeFrom((ru.itis.hr.grpc.pb.cv.Cv.CV)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ru.itis.hr.grpc.pb.cv.Cv.CV other) {
        if (other == ru.itis.hr.grpc.pb.cv.Cv.CV.getDefaultInstance()) return this;
        if (!other.getCandidateName().isEmpty()) {
          candidateName_ = other.candidateName_;
          onChanged();
        }
        if (other.getCandidateAge() != 0) {
          setCandidateAge(other.getCandidateAge());
        }
        if (other.getExperience() != 0) {
          setExperience(other.getExperience());
        }
        if (!other.skills_.isEmpty()) {
          if (skills_.isEmpty()) {
            skills_ = other.skills_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureSkillsIsMutable();
            skills_.addAll(other.skills_);
          }
          onChanged();
        }
        if (!other.getExperienceDescription().isEmpty()) {
          experienceDescription_ = other.experienceDescription_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ru.itis.hr.grpc.pb.cv.Cv.CV parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ru.itis.hr.grpc.pb.cv.Cv.CV) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object candidateName_ = "";
      /**
       * <code>string candidateName = 1;</code>
       * @return The candidateName.
       */
      public java.lang.String getCandidateName() {
        java.lang.Object ref = candidateName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          candidateName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string candidateName = 1;</code>
       * @return The bytes for candidateName.
       */
      public com.google.protobuf.ByteString
          getCandidateNameBytes() {
        java.lang.Object ref = candidateName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          candidateName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string candidateName = 1;</code>
       * @param value The candidateName to set.
       * @return This builder for chaining.
       */
      public Builder setCandidateName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        candidateName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string candidateName = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCandidateName() {
        
        candidateName_ = getDefaultInstance().getCandidateName();
        onChanged();
        return this;
      }
      /**
       * <code>string candidateName = 1;</code>
       * @param value The bytes for candidateName to set.
       * @return This builder for chaining.
       */
      public Builder setCandidateNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        candidateName_ = value;
        onChanged();
        return this;
      }

      private int candidateAge_ ;
      /**
       * <code>uint32 candidateAge = 2;</code>
       * @return The candidateAge.
       */
      @java.lang.Override
      public int getCandidateAge() {
        return candidateAge_;
      }
      /**
       * <code>uint32 candidateAge = 2;</code>
       * @param value The candidateAge to set.
       * @return This builder for chaining.
       */
      public Builder setCandidateAge(int value) {
        
        candidateAge_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 candidateAge = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearCandidateAge() {
        
        candidateAge_ = 0;
        onChanged();
        return this;
      }

      private int experience_ ;
      /**
       * <code>uint32 experience = 3;</code>
       * @return The experience.
       */
      @java.lang.Override
      public int getExperience() {
        return experience_;
      }
      /**
       * <code>uint32 experience = 3;</code>
       * @param value The experience to set.
       * @return This builder for chaining.
       */
      public Builder setExperience(int value) {
        
        experience_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 experience = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearExperience() {
        
        experience_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList skills_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureSkillsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          skills_ = new com.google.protobuf.LazyStringArrayList(skills_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated string skills = 4;</code>
       * @return A list containing the skills.
       */
      public com.google.protobuf.ProtocolStringList
          getSkillsList() {
        return skills_.getUnmodifiableView();
      }
      /**
       * <code>repeated string skills = 4;</code>
       * @return The count of skills.
       */
      public int getSkillsCount() {
        return skills_.size();
      }
      /**
       * <code>repeated string skills = 4;</code>
       * @param index The index of the element to return.
       * @return The skills at the given index.
       */
      public java.lang.String getSkills(int index) {
        return skills_.get(index);
      }
      /**
       * <code>repeated string skills = 4;</code>
       * @param index The index of the value to return.
       * @return The bytes of the skills at the given index.
       */
      public com.google.protobuf.ByteString
          getSkillsBytes(int index) {
        return skills_.getByteString(index);
      }
      /**
       * <code>repeated string skills = 4;</code>
       * @param index The index to set the value at.
       * @param value The skills to set.
       * @return This builder for chaining.
       */
      public Builder setSkills(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureSkillsIsMutable();
        skills_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string skills = 4;</code>
       * @param value The skills to add.
       * @return This builder for chaining.
       */
      public Builder addSkills(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureSkillsIsMutable();
        skills_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string skills = 4;</code>
       * @param values The skills to add.
       * @return This builder for chaining.
       */
      public Builder addAllSkills(
          java.lang.Iterable<java.lang.String> values) {
        ensureSkillsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, skills_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string skills = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearSkills() {
        skills_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string skills = 4;</code>
       * @param value The bytes of the skills to add.
       * @return This builder for chaining.
       */
      public Builder addSkillsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureSkillsIsMutable();
        skills_.add(value);
        onChanged();
        return this;
      }

      private java.lang.Object experienceDescription_ = "";
      /**
       * <code>string experienceDescription = 5;</code>
       * @return The experienceDescription.
       */
      public java.lang.String getExperienceDescription() {
        java.lang.Object ref = experienceDescription_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          experienceDescription_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string experienceDescription = 5;</code>
       * @return The bytes for experienceDescription.
       */
      public com.google.protobuf.ByteString
          getExperienceDescriptionBytes() {
        java.lang.Object ref = experienceDescription_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          experienceDescription_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string experienceDescription = 5;</code>
       * @param value The experienceDescription to set.
       * @return This builder for chaining.
       */
      public Builder setExperienceDescription(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        experienceDescription_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string experienceDescription = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearExperienceDescription() {
        
        experienceDescription_ = getDefaultInstance().getExperienceDescription();
        onChanged();
        return this;
      }
      /**
       * <code>string experienceDescription = 5;</code>
       * @param value The bytes for experienceDescription to set.
       * @return This builder for chaining.
       */
      public Builder setExperienceDescriptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        experienceDescription_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:CV)
    }

    // @@protoc_insertion_point(class_scope:CV)
    private static final ru.itis.hr.grpc.pb.cv.Cv.CV DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ru.itis.hr.grpc.pb.cv.Cv.CV();
    }

    public static ru.itis.hr.grpc.pb.cv.Cv.CV getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CV>
        PARSER = new com.google.protobuf.AbstractParser<CV>() {
      @java.lang.Override
      public CV parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CV(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CV> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CV> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ru.itis.hr.grpc.pb.cv.Cv.CV getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CVResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CVResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .CV cvs = 1;</code>
     */
    java.util.List<ru.itis.hr.grpc.pb.cv.Cv.CV> 
        getCvsList();
    /**
     * <code>repeated .CV cvs = 1;</code>
     */
    ru.itis.hr.grpc.pb.cv.Cv.CV getCvs(int index);
    /**
     * <code>repeated .CV cvs = 1;</code>
     */
    int getCvsCount();
    /**
     * <code>repeated .CV cvs = 1;</code>
     */
    java.util.List<? extends ru.itis.hr.grpc.pb.cv.Cv.CVOrBuilder> 
        getCvsOrBuilderList();
    /**
     * <code>repeated .CV cvs = 1;</code>
     */
    ru.itis.hr.grpc.pb.cv.Cv.CVOrBuilder getCvsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code CVResponse}
   */
  public static final class CVResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:CVResponse)
      CVResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CVResponse.newBuilder() to construct.
    private CVResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CVResponse() {
      cvs_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new CVResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CVResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                cvs_ = new java.util.ArrayList<ru.itis.hr.grpc.pb.cv.Cv.CV>();
                mutable_bitField0_ |= 0x00000001;
              }
              cvs_.add(
                  input.readMessage(ru.itis.hr.grpc.pb.cv.Cv.CV.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          cvs_ = java.util.Collections.unmodifiableList(cvs_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ru.itis.hr.grpc.pb.cv.Cv.internal_static_CVResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ru.itis.hr.grpc.pb.cv.Cv.internal_static_CVResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ru.itis.hr.grpc.pb.cv.Cv.CVResponse.class, ru.itis.hr.grpc.pb.cv.Cv.CVResponse.Builder.class);
    }

    public static final int CVS_FIELD_NUMBER = 1;
    private java.util.List<ru.itis.hr.grpc.pb.cv.Cv.CV> cvs_;
    /**
     * <code>repeated .CV cvs = 1;</code>
     */
    @java.lang.Override
    public java.util.List<ru.itis.hr.grpc.pb.cv.Cv.CV> getCvsList() {
      return cvs_;
    }
    /**
     * <code>repeated .CV cvs = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends ru.itis.hr.grpc.pb.cv.Cv.CVOrBuilder> 
        getCvsOrBuilderList() {
      return cvs_;
    }
    /**
     * <code>repeated .CV cvs = 1;</code>
     */
    @java.lang.Override
    public int getCvsCount() {
      return cvs_.size();
    }
    /**
     * <code>repeated .CV cvs = 1;</code>
     */
    @java.lang.Override
    public ru.itis.hr.grpc.pb.cv.Cv.CV getCvs(int index) {
      return cvs_.get(index);
    }
    /**
     * <code>repeated .CV cvs = 1;</code>
     */
    @java.lang.Override
    public ru.itis.hr.grpc.pb.cv.Cv.CVOrBuilder getCvsOrBuilder(
        int index) {
      return cvs_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < cvs_.size(); i++) {
        output.writeMessage(1, cvs_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < cvs_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, cvs_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ru.itis.hr.grpc.pb.cv.Cv.CVResponse)) {
        return super.equals(obj);
      }
      ru.itis.hr.grpc.pb.cv.Cv.CVResponse other = (ru.itis.hr.grpc.pb.cv.Cv.CVResponse) obj;

      if (!getCvsList()
          .equals(other.getCvsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getCvsCount() > 0) {
        hash = (37 * hash) + CVS_FIELD_NUMBER;
        hash = (53 * hash) + getCvsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ru.itis.hr.grpc.pb.cv.Cv.CVResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.itis.hr.grpc.pb.cv.Cv.CVResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.itis.hr.grpc.pb.cv.Cv.CVResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.itis.hr.grpc.pb.cv.Cv.CVResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.itis.hr.grpc.pb.cv.Cv.CVResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.itis.hr.grpc.pb.cv.Cv.CVResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.itis.hr.grpc.pb.cv.Cv.CVResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ru.itis.hr.grpc.pb.cv.Cv.CVResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ru.itis.hr.grpc.pb.cv.Cv.CVResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ru.itis.hr.grpc.pb.cv.Cv.CVResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ru.itis.hr.grpc.pb.cv.Cv.CVResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ru.itis.hr.grpc.pb.cv.Cv.CVResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ru.itis.hr.grpc.pb.cv.Cv.CVResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CVResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CVResponse)
        ru.itis.hr.grpc.pb.cv.Cv.CVResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ru.itis.hr.grpc.pb.cv.Cv.internal_static_CVResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ru.itis.hr.grpc.pb.cv.Cv.internal_static_CVResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ru.itis.hr.grpc.pb.cv.Cv.CVResponse.class, ru.itis.hr.grpc.pb.cv.Cv.CVResponse.Builder.class);
      }

      // Construct using ru.itis.hr.grpc.pb.cv.Cv.CVResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getCvsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (cvsBuilder_ == null) {
          cvs_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          cvsBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ru.itis.hr.grpc.pb.cv.Cv.internal_static_CVResponse_descriptor;
      }

      @java.lang.Override
      public ru.itis.hr.grpc.pb.cv.Cv.CVResponse getDefaultInstanceForType() {
        return ru.itis.hr.grpc.pb.cv.Cv.CVResponse.getDefaultInstance();
      }

      @java.lang.Override
      public ru.itis.hr.grpc.pb.cv.Cv.CVResponse build() {
        ru.itis.hr.grpc.pb.cv.Cv.CVResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ru.itis.hr.grpc.pb.cv.Cv.CVResponse buildPartial() {
        ru.itis.hr.grpc.pb.cv.Cv.CVResponse result = new ru.itis.hr.grpc.pb.cv.Cv.CVResponse(this);
        int from_bitField0_ = bitField0_;
        if (cvsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            cvs_ = java.util.Collections.unmodifiableList(cvs_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.cvs_ = cvs_;
        } else {
          result.cvs_ = cvsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ru.itis.hr.grpc.pb.cv.Cv.CVResponse) {
          return mergeFrom((ru.itis.hr.grpc.pb.cv.Cv.CVResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ru.itis.hr.grpc.pb.cv.Cv.CVResponse other) {
        if (other == ru.itis.hr.grpc.pb.cv.Cv.CVResponse.getDefaultInstance()) return this;
        if (cvsBuilder_ == null) {
          if (!other.cvs_.isEmpty()) {
            if (cvs_.isEmpty()) {
              cvs_ = other.cvs_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureCvsIsMutable();
              cvs_.addAll(other.cvs_);
            }
            onChanged();
          }
        } else {
          if (!other.cvs_.isEmpty()) {
            if (cvsBuilder_.isEmpty()) {
              cvsBuilder_.dispose();
              cvsBuilder_ = null;
              cvs_ = other.cvs_;
              bitField0_ = (bitField0_ & ~0x00000001);
              cvsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getCvsFieldBuilder() : null;
            } else {
              cvsBuilder_.addAllMessages(other.cvs_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ru.itis.hr.grpc.pb.cv.Cv.CVResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ru.itis.hr.grpc.pb.cv.Cv.CVResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<ru.itis.hr.grpc.pb.cv.Cv.CV> cvs_ =
        java.util.Collections.emptyList();
      private void ensureCvsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          cvs_ = new java.util.ArrayList<ru.itis.hr.grpc.pb.cv.Cv.CV>(cvs_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          ru.itis.hr.grpc.pb.cv.Cv.CV, ru.itis.hr.grpc.pb.cv.Cv.CV.Builder, ru.itis.hr.grpc.pb.cv.Cv.CVOrBuilder> cvsBuilder_;

      /**
       * <code>repeated .CV cvs = 1;</code>
       */
      public java.util.List<ru.itis.hr.grpc.pb.cv.Cv.CV> getCvsList() {
        if (cvsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(cvs_);
        } else {
          return cvsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .CV cvs = 1;</code>
       */
      public int getCvsCount() {
        if (cvsBuilder_ == null) {
          return cvs_.size();
        } else {
          return cvsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .CV cvs = 1;</code>
       */
      public ru.itis.hr.grpc.pb.cv.Cv.CV getCvs(int index) {
        if (cvsBuilder_ == null) {
          return cvs_.get(index);
        } else {
          return cvsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .CV cvs = 1;</code>
       */
      public Builder setCvs(
          int index, ru.itis.hr.grpc.pb.cv.Cv.CV value) {
        if (cvsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCvsIsMutable();
          cvs_.set(index, value);
          onChanged();
        } else {
          cvsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .CV cvs = 1;</code>
       */
      public Builder setCvs(
          int index, ru.itis.hr.grpc.pb.cv.Cv.CV.Builder builderForValue) {
        if (cvsBuilder_ == null) {
          ensureCvsIsMutable();
          cvs_.set(index, builderForValue.build());
          onChanged();
        } else {
          cvsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .CV cvs = 1;</code>
       */
      public Builder addCvs(ru.itis.hr.grpc.pb.cv.Cv.CV value) {
        if (cvsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCvsIsMutable();
          cvs_.add(value);
          onChanged();
        } else {
          cvsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .CV cvs = 1;</code>
       */
      public Builder addCvs(
          int index, ru.itis.hr.grpc.pb.cv.Cv.CV value) {
        if (cvsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCvsIsMutable();
          cvs_.add(index, value);
          onChanged();
        } else {
          cvsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .CV cvs = 1;</code>
       */
      public Builder addCvs(
          ru.itis.hr.grpc.pb.cv.Cv.CV.Builder builderForValue) {
        if (cvsBuilder_ == null) {
          ensureCvsIsMutable();
          cvs_.add(builderForValue.build());
          onChanged();
        } else {
          cvsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .CV cvs = 1;</code>
       */
      public Builder addCvs(
          int index, ru.itis.hr.grpc.pb.cv.Cv.CV.Builder builderForValue) {
        if (cvsBuilder_ == null) {
          ensureCvsIsMutable();
          cvs_.add(index, builderForValue.build());
          onChanged();
        } else {
          cvsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .CV cvs = 1;</code>
       */
      public Builder addAllCvs(
          java.lang.Iterable<? extends ru.itis.hr.grpc.pb.cv.Cv.CV> values) {
        if (cvsBuilder_ == null) {
          ensureCvsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, cvs_);
          onChanged();
        } else {
          cvsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .CV cvs = 1;</code>
       */
      public Builder clearCvs() {
        if (cvsBuilder_ == null) {
          cvs_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          cvsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .CV cvs = 1;</code>
       */
      public Builder removeCvs(int index) {
        if (cvsBuilder_ == null) {
          ensureCvsIsMutable();
          cvs_.remove(index);
          onChanged();
        } else {
          cvsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .CV cvs = 1;</code>
       */
      public ru.itis.hr.grpc.pb.cv.Cv.CV.Builder getCvsBuilder(
          int index) {
        return getCvsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .CV cvs = 1;</code>
       */
      public ru.itis.hr.grpc.pb.cv.Cv.CVOrBuilder getCvsOrBuilder(
          int index) {
        if (cvsBuilder_ == null) {
          return cvs_.get(index);  } else {
          return cvsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .CV cvs = 1;</code>
       */
      public java.util.List<? extends ru.itis.hr.grpc.pb.cv.Cv.CVOrBuilder> 
           getCvsOrBuilderList() {
        if (cvsBuilder_ != null) {
          return cvsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(cvs_);
        }
      }
      /**
       * <code>repeated .CV cvs = 1;</code>
       */
      public ru.itis.hr.grpc.pb.cv.Cv.CV.Builder addCvsBuilder() {
        return getCvsFieldBuilder().addBuilder(
            ru.itis.hr.grpc.pb.cv.Cv.CV.getDefaultInstance());
      }
      /**
       * <code>repeated .CV cvs = 1;</code>
       */
      public ru.itis.hr.grpc.pb.cv.Cv.CV.Builder addCvsBuilder(
          int index) {
        return getCvsFieldBuilder().addBuilder(
            index, ru.itis.hr.grpc.pb.cv.Cv.CV.getDefaultInstance());
      }
      /**
       * <code>repeated .CV cvs = 1;</code>
       */
      public java.util.List<ru.itis.hr.grpc.pb.cv.Cv.CV.Builder> 
           getCvsBuilderList() {
        return getCvsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          ru.itis.hr.grpc.pb.cv.Cv.CV, ru.itis.hr.grpc.pb.cv.Cv.CV.Builder, ru.itis.hr.grpc.pb.cv.Cv.CVOrBuilder> 
          getCvsFieldBuilder() {
        if (cvsBuilder_ == null) {
          cvsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              ru.itis.hr.grpc.pb.cv.Cv.CV, ru.itis.hr.grpc.pb.cv.Cv.CV.Builder, ru.itis.hr.grpc.pb.cv.Cv.CVOrBuilder>(
                  cvs_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          cvs_ = null;
        }
        return cvsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:CVResponse)
    }

    // @@protoc_insertion_point(class_scope:CVResponse)
    private static final ru.itis.hr.grpc.pb.cv.Cv.CVResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ru.itis.hr.grpc.pb.cv.Cv.CVResponse();
    }

    public static ru.itis.hr.grpc.pb.cv.Cv.CVResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CVResponse>
        PARSER = new com.google.protobuf.AbstractParser<CVResponse>() {
      @java.lang.Override
      public CVResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CVResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CVResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CVResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ru.itis.hr.grpc.pb.cv.Cv.CVResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CVRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CVRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CV_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CV_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CVResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CVResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\010cv.proto\"\033\n\tCVRequest\022\016\n\006skills\030\001 \003(\t\"" +
      "t\n\002CV\022\025\n\rcandidateName\030\001 \001(\t\022\024\n\014candidat" +
      "eAge\030\002 \001(\r\022\022\n\nexperience\030\003 \001(\r\022\016\n\006skills" +
      "\030\004 \003(\t\022\035\n\025experienceDescription\030\005 \001(\t\"\036\n" +
      "\nCVResponse\022\020\n\003cvs\030\001 \003(\0132\003.CV2/\n\tCVServi" +
      "ce\022\"\n\005GetCV\022\n.CVRequest\032\013.CVResponse\"\000B\027" +
      "\n\025ru.itis.hr.grpc.pb.cvb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_CVRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CVRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CVRequest_descriptor,
        new java.lang.String[] { "Skills", });
    internal_static_CV_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_CV_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CV_descriptor,
        new java.lang.String[] { "CandidateName", "CandidateAge", "Experience", "Skills", "ExperienceDescription", });
    internal_static_CVResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_CVResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CVResponse_descriptor,
        new java.lang.String[] { "Cvs", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
