// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: job.proto

package ru.itis.hr.grpc.pb.job;

public final class JobOuterClass {
  private JobOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface JobRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:JobRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 page = 1;</code>
     * @return The page.
     */
    long getPage();
  }
  /**
   * Protobuf type {@code JobRequest}
   */
  public static final class JobRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:JobRequest)
      JobRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use JobRequest.newBuilder() to construct.
    private JobRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private JobRequest() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new JobRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private JobRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              page_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ru.itis.hr.grpc.pb.job.JobOuterClass.internal_static_JobRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ru.itis.hr.grpc.pb.job.JobOuterClass.internal_static_JobRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ru.itis.hr.grpc.pb.job.JobOuterClass.JobRequest.class, ru.itis.hr.grpc.pb.job.JobOuterClass.JobRequest.Builder.class);
    }

    public static final int PAGE_FIELD_NUMBER = 1;
    private long page_;
    /**
     * <code>int64 page = 1;</code>
     * @return The page.
     */
    @java.lang.Override
    public long getPage() {
      return page_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (page_ != 0L) {
        output.writeInt64(1, page_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (page_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, page_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ru.itis.hr.grpc.pb.job.JobOuterClass.JobRequest)) {
        return super.equals(obj);
      }
      ru.itis.hr.grpc.pb.job.JobOuterClass.JobRequest other = (ru.itis.hr.grpc.pb.job.JobOuterClass.JobRequest) obj;

      if (getPage()
          != other.getPage()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PAGE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getPage());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ru.itis.hr.grpc.pb.job.JobOuterClass.JobRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.itis.hr.grpc.pb.job.JobOuterClass.JobRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.itis.hr.grpc.pb.job.JobOuterClass.JobRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.itis.hr.grpc.pb.job.JobOuterClass.JobRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.itis.hr.grpc.pb.job.JobOuterClass.JobRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.itis.hr.grpc.pb.job.JobOuterClass.JobRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.itis.hr.grpc.pb.job.JobOuterClass.JobRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ru.itis.hr.grpc.pb.job.JobOuterClass.JobRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ru.itis.hr.grpc.pb.job.JobOuterClass.JobRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ru.itis.hr.grpc.pb.job.JobOuterClass.JobRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ru.itis.hr.grpc.pb.job.JobOuterClass.JobRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ru.itis.hr.grpc.pb.job.JobOuterClass.JobRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ru.itis.hr.grpc.pb.job.JobOuterClass.JobRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code JobRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:JobRequest)
        ru.itis.hr.grpc.pb.job.JobOuterClass.JobRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ru.itis.hr.grpc.pb.job.JobOuterClass.internal_static_JobRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ru.itis.hr.grpc.pb.job.JobOuterClass.internal_static_JobRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ru.itis.hr.grpc.pb.job.JobOuterClass.JobRequest.class, ru.itis.hr.grpc.pb.job.JobOuterClass.JobRequest.Builder.class);
      }

      // Construct using ru.itis.hr.grpc.pb.job.JobOuterClass.JobRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        page_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ru.itis.hr.grpc.pb.job.JobOuterClass.internal_static_JobRequest_descriptor;
      }

      @java.lang.Override
      public ru.itis.hr.grpc.pb.job.JobOuterClass.JobRequest getDefaultInstanceForType() {
        return ru.itis.hr.grpc.pb.job.JobOuterClass.JobRequest.getDefaultInstance();
      }

      @java.lang.Override
      public ru.itis.hr.grpc.pb.job.JobOuterClass.JobRequest build() {
        ru.itis.hr.grpc.pb.job.JobOuterClass.JobRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ru.itis.hr.grpc.pb.job.JobOuterClass.JobRequest buildPartial() {
        ru.itis.hr.grpc.pb.job.JobOuterClass.JobRequest result = new ru.itis.hr.grpc.pb.job.JobOuterClass.JobRequest(this);
        result.page_ = page_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ru.itis.hr.grpc.pb.job.JobOuterClass.JobRequest) {
          return mergeFrom((ru.itis.hr.grpc.pb.job.JobOuterClass.JobRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ru.itis.hr.grpc.pb.job.JobOuterClass.JobRequest other) {
        if (other == ru.itis.hr.grpc.pb.job.JobOuterClass.JobRequest.getDefaultInstance()) return this;
        if (other.getPage() != 0L) {
          setPage(other.getPage());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ru.itis.hr.grpc.pb.job.JobOuterClass.JobRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ru.itis.hr.grpc.pb.job.JobOuterClass.JobRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long page_ ;
      /**
       * <code>int64 page = 1;</code>
       * @return The page.
       */
      @java.lang.Override
      public long getPage() {
        return page_;
      }
      /**
       * <code>int64 page = 1;</code>
       * @param value The page to set.
       * @return This builder for chaining.
       */
      public Builder setPage(long value) {
        
        page_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 page = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearPage() {
        
        page_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:JobRequest)
    }

    // @@protoc_insertion_point(class_scope:JobRequest)
    private static final ru.itis.hr.grpc.pb.job.JobOuterClass.JobRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ru.itis.hr.grpc.pb.job.JobOuterClass.JobRequest();
    }

    public static ru.itis.hr.grpc.pb.job.JobOuterClass.JobRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<JobRequest>
        PARSER = new com.google.protobuf.AbstractParser<JobRequest>() {
      @java.lang.Override
      public JobRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new JobRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<JobRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<JobRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ru.itis.hr.grpc.pb.job.JobOuterClass.JobRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface JobOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Job)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string jobDescription = 1;</code>
     * @return The jobDescription.
     */
    java.lang.String getJobDescription();
    /**
     * <code>string jobDescription = 1;</code>
     * @return The bytes for jobDescription.
     */
    com.google.protobuf.ByteString
        getJobDescriptionBytes();

    /**
     * <code>uint32 salary = 2;</code>
     * @return The salary.
     */
    int getSalary();

    /**
     * <code>uint32 experience = 3;</code>
     * @return The experience.
     */
    int getExperience();

    /**
     * <code>repeated string skills = 4;</code>
     * @return A list containing the skills.
     */
    java.util.List<java.lang.String>
        getSkillsList();
    /**
     * <code>repeated string skills = 4;</code>
     * @return The count of skills.
     */
    int getSkillsCount();
    /**
     * <code>repeated string skills = 4;</code>
     * @param index The index of the element to return.
     * @return The skills at the given index.
     */
    java.lang.String getSkills(int index);
    /**
     * <code>repeated string skills = 4;</code>
     * @param index The index of the value to return.
     * @return The bytes of the skills at the given index.
     */
    com.google.protobuf.ByteString
        getSkillsBytes(int index);
  }
  /**
   * Protobuf type {@code Job}
   */
  public static final class Job extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Job)
      JobOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Job.newBuilder() to construct.
    private Job(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Job() {
      jobDescription_ = "";
      skills_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Job();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Job(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              jobDescription_ = s;
              break;
            }
            case 16: {

              salary_ = input.readUInt32();
              break;
            }
            case 24: {

              experience_ = input.readUInt32();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                skills_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              skills_.add(s);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          skills_ = skills_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ru.itis.hr.grpc.pb.job.JobOuterClass.internal_static_Job_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ru.itis.hr.grpc.pb.job.JobOuterClass.internal_static_Job_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ru.itis.hr.grpc.pb.job.JobOuterClass.Job.class, ru.itis.hr.grpc.pb.job.JobOuterClass.Job.Builder.class);
    }

    public static final int JOBDESCRIPTION_FIELD_NUMBER = 1;
    private volatile java.lang.Object jobDescription_;
    /**
     * <code>string jobDescription = 1;</code>
     * @return The jobDescription.
     */
    @java.lang.Override
    public java.lang.String getJobDescription() {
      java.lang.Object ref = jobDescription_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        jobDescription_ = s;
        return s;
      }
    }
    /**
     * <code>string jobDescription = 1;</code>
     * @return The bytes for jobDescription.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getJobDescriptionBytes() {
      java.lang.Object ref = jobDescription_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        jobDescription_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SALARY_FIELD_NUMBER = 2;
    private int salary_;
    /**
     * <code>uint32 salary = 2;</code>
     * @return The salary.
     */
    @java.lang.Override
    public int getSalary() {
      return salary_;
    }

    public static final int EXPERIENCE_FIELD_NUMBER = 3;
    private int experience_;
    /**
     * <code>uint32 experience = 3;</code>
     * @return The experience.
     */
    @java.lang.Override
    public int getExperience() {
      return experience_;
    }

    public static final int SKILLS_FIELD_NUMBER = 4;
    private com.google.protobuf.LazyStringList skills_;
    /**
     * <code>repeated string skills = 4;</code>
     * @return A list containing the skills.
     */
    public com.google.protobuf.ProtocolStringList
        getSkillsList() {
      return skills_;
    }
    /**
     * <code>repeated string skills = 4;</code>
     * @return The count of skills.
     */
    public int getSkillsCount() {
      return skills_.size();
    }
    /**
     * <code>repeated string skills = 4;</code>
     * @param index The index of the element to return.
     * @return The skills at the given index.
     */
    public java.lang.String getSkills(int index) {
      return skills_.get(index);
    }
    /**
     * <code>repeated string skills = 4;</code>
     * @param index The index of the value to return.
     * @return The bytes of the skills at the given index.
     */
    public com.google.protobuf.ByteString
        getSkillsBytes(int index) {
      return skills_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getJobDescriptionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, jobDescription_);
      }
      if (salary_ != 0) {
        output.writeUInt32(2, salary_);
      }
      if (experience_ != 0) {
        output.writeUInt32(3, experience_);
      }
      for (int i = 0; i < skills_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, skills_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getJobDescriptionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, jobDescription_);
      }
      if (salary_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, salary_);
      }
      if (experience_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, experience_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < skills_.size(); i++) {
          dataSize += computeStringSizeNoTag(skills_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getSkillsList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ru.itis.hr.grpc.pb.job.JobOuterClass.Job)) {
        return super.equals(obj);
      }
      ru.itis.hr.grpc.pb.job.JobOuterClass.Job other = (ru.itis.hr.grpc.pb.job.JobOuterClass.Job) obj;

      if (!getJobDescription()
          .equals(other.getJobDescription())) return false;
      if (getSalary()
          != other.getSalary()) return false;
      if (getExperience()
          != other.getExperience()) return false;
      if (!getSkillsList()
          .equals(other.getSkillsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + JOBDESCRIPTION_FIELD_NUMBER;
      hash = (53 * hash) + getJobDescription().hashCode();
      hash = (37 * hash) + SALARY_FIELD_NUMBER;
      hash = (53 * hash) + getSalary();
      hash = (37 * hash) + EXPERIENCE_FIELD_NUMBER;
      hash = (53 * hash) + getExperience();
      if (getSkillsCount() > 0) {
        hash = (37 * hash) + SKILLS_FIELD_NUMBER;
        hash = (53 * hash) + getSkillsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ru.itis.hr.grpc.pb.job.JobOuterClass.Job parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.itis.hr.grpc.pb.job.JobOuterClass.Job parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.itis.hr.grpc.pb.job.JobOuterClass.Job parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.itis.hr.grpc.pb.job.JobOuterClass.Job parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.itis.hr.grpc.pb.job.JobOuterClass.Job parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.itis.hr.grpc.pb.job.JobOuterClass.Job parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.itis.hr.grpc.pb.job.JobOuterClass.Job parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ru.itis.hr.grpc.pb.job.JobOuterClass.Job parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ru.itis.hr.grpc.pb.job.JobOuterClass.Job parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ru.itis.hr.grpc.pb.job.JobOuterClass.Job parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ru.itis.hr.grpc.pb.job.JobOuterClass.Job parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ru.itis.hr.grpc.pb.job.JobOuterClass.Job parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ru.itis.hr.grpc.pb.job.JobOuterClass.Job prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Job}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Job)
        ru.itis.hr.grpc.pb.job.JobOuterClass.JobOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ru.itis.hr.grpc.pb.job.JobOuterClass.internal_static_Job_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ru.itis.hr.grpc.pb.job.JobOuterClass.internal_static_Job_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ru.itis.hr.grpc.pb.job.JobOuterClass.Job.class, ru.itis.hr.grpc.pb.job.JobOuterClass.Job.Builder.class);
      }

      // Construct using ru.itis.hr.grpc.pb.job.JobOuterClass.Job.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        jobDescription_ = "";

        salary_ = 0;

        experience_ = 0;

        skills_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ru.itis.hr.grpc.pb.job.JobOuterClass.internal_static_Job_descriptor;
      }

      @java.lang.Override
      public ru.itis.hr.grpc.pb.job.JobOuterClass.Job getDefaultInstanceForType() {
        return ru.itis.hr.grpc.pb.job.JobOuterClass.Job.getDefaultInstance();
      }

      @java.lang.Override
      public ru.itis.hr.grpc.pb.job.JobOuterClass.Job build() {
        ru.itis.hr.grpc.pb.job.JobOuterClass.Job result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ru.itis.hr.grpc.pb.job.JobOuterClass.Job buildPartial() {
        ru.itis.hr.grpc.pb.job.JobOuterClass.Job result = new ru.itis.hr.grpc.pb.job.JobOuterClass.Job(this);
        int from_bitField0_ = bitField0_;
        result.jobDescription_ = jobDescription_;
        result.salary_ = salary_;
        result.experience_ = experience_;
        if (((bitField0_ & 0x00000001) != 0)) {
          skills_ = skills_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.skills_ = skills_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ru.itis.hr.grpc.pb.job.JobOuterClass.Job) {
          return mergeFrom((ru.itis.hr.grpc.pb.job.JobOuterClass.Job)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ru.itis.hr.grpc.pb.job.JobOuterClass.Job other) {
        if (other == ru.itis.hr.grpc.pb.job.JobOuterClass.Job.getDefaultInstance()) return this;
        if (!other.getJobDescription().isEmpty()) {
          jobDescription_ = other.jobDescription_;
          onChanged();
        }
        if (other.getSalary() != 0) {
          setSalary(other.getSalary());
        }
        if (other.getExperience() != 0) {
          setExperience(other.getExperience());
        }
        if (!other.skills_.isEmpty()) {
          if (skills_.isEmpty()) {
            skills_ = other.skills_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureSkillsIsMutable();
            skills_.addAll(other.skills_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ru.itis.hr.grpc.pb.job.JobOuterClass.Job parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ru.itis.hr.grpc.pb.job.JobOuterClass.Job) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object jobDescription_ = "";
      /**
       * <code>string jobDescription = 1;</code>
       * @return The jobDescription.
       */
      public java.lang.String getJobDescription() {
        java.lang.Object ref = jobDescription_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          jobDescription_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string jobDescription = 1;</code>
       * @return The bytes for jobDescription.
       */
      public com.google.protobuf.ByteString
          getJobDescriptionBytes() {
        java.lang.Object ref = jobDescription_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          jobDescription_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string jobDescription = 1;</code>
       * @param value The jobDescription to set.
       * @return This builder for chaining.
       */
      public Builder setJobDescription(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        jobDescription_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string jobDescription = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearJobDescription() {
        
        jobDescription_ = getDefaultInstance().getJobDescription();
        onChanged();
        return this;
      }
      /**
       * <code>string jobDescription = 1;</code>
       * @param value The bytes for jobDescription to set.
       * @return This builder for chaining.
       */
      public Builder setJobDescriptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        jobDescription_ = value;
        onChanged();
        return this;
      }

      private int salary_ ;
      /**
       * <code>uint32 salary = 2;</code>
       * @return The salary.
       */
      @java.lang.Override
      public int getSalary() {
        return salary_;
      }
      /**
       * <code>uint32 salary = 2;</code>
       * @param value The salary to set.
       * @return This builder for chaining.
       */
      public Builder setSalary(int value) {
        
        salary_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 salary = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearSalary() {
        
        salary_ = 0;
        onChanged();
        return this;
      }

      private int experience_ ;
      /**
       * <code>uint32 experience = 3;</code>
       * @return The experience.
       */
      @java.lang.Override
      public int getExperience() {
        return experience_;
      }
      /**
       * <code>uint32 experience = 3;</code>
       * @param value The experience to set.
       * @return This builder for chaining.
       */
      public Builder setExperience(int value) {
        
        experience_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 experience = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearExperience() {
        
        experience_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList skills_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureSkillsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          skills_ = new com.google.protobuf.LazyStringArrayList(skills_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated string skills = 4;</code>
       * @return A list containing the skills.
       */
      public com.google.protobuf.ProtocolStringList
          getSkillsList() {
        return skills_.getUnmodifiableView();
      }
      /**
       * <code>repeated string skills = 4;</code>
       * @return The count of skills.
       */
      public int getSkillsCount() {
        return skills_.size();
      }
      /**
       * <code>repeated string skills = 4;</code>
       * @param index The index of the element to return.
       * @return The skills at the given index.
       */
      public java.lang.String getSkills(int index) {
        return skills_.get(index);
      }
      /**
       * <code>repeated string skills = 4;</code>
       * @param index The index of the value to return.
       * @return The bytes of the skills at the given index.
       */
      public com.google.protobuf.ByteString
          getSkillsBytes(int index) {
        return skills_.getByteString(index);
      }
      /**
       * <code>repeated string skills = 4;</code>
       * @param index The index to set the value at.
       * @param value The skills to set.
       * @return This builder for chaining.
       */
      public Builder setSkills(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureSkillsIsMutable();
        skills_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string skills = 4;</code>
       * @param value The skills to add.
       * @return This builder for chaining.
       */
      public Builder addSkills(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureSkillsIsMutable();
        skills_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string skills = 4;</code>
       * @param values The skills to add.
       * @return This builder for chaining.
       */
      public Builder addAllSkills(
          java.lang.Iterable<java.lang.String> values) {
        ensureSkillsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, skills_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string skills = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearSkills() {
        skills_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string skills = 4;</code>
       * @param value The bytes of the skills to add.
       * @return This builder for chaining.
       */
      public Builder addSkillsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureSkillsIsMutable();
        skills_.add(value);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Job)
    }

    // @@protoc_insertion_point(class_scope:Job)
    private static final ru.itis.hr.grpc.pb.job.JobOuterClass.Job DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ru.itis.hr.grpc.pb.job.JobOuterClass.Job();
    }

    public static ru.itis.hr.grpc.pb.job.JobOuterClass.Job getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Job>
        PARSER = new com.google.protobuf.AbstractParser<Job>() {
      @java.lang.Override
      public Job parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Job(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Job> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Job> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ru.itis.hr.grpc.pb.job.JobOuterClass.Job getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface JobResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:JobResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .Job jobs = 1;</code>
     */
    java.util.List<ru.itis.hr.grpc.pb.job.JobOuterClass.Job> 
        getJobsList();
    /**
     * <code>repeated .Job jobs = 1;</code>
     */
    ru.itis.hr.grpc.pb.job.JobOuterClass.Job getJobs(int index);
    /**
     * <code>repeated .Job jobs = 1;</code>
     */
    int getJobsCount();
    /**
     * <code>repeated .Job jobs = 1;</code>
     */
    java.util.List<? extends ru.itis.hr.grpc.pb.job.JobOuterClass.JobOrBuilder> 
        getJobsOrBuilderList();
    /**
     * <code>repeated .Job jobs = 1;</code>
     */
    ru.itis.hr.grpc.pb.job.JobOuterClass.JobOrBuilder getJobsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code JobResponse}
   */
  public static final class JobResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:JobResponse)
      JobResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use JobResponse.newBuilder() to construct.
    private JobResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private JobResponse() {
      jobs_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new JobResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private JobResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                jobs_ = new java.util.ArrayList<ru.itis.hr.grpc.pb.job.JobOuterClass.Job>();
                mutable_bitField0_ |= 0x00000001;
              }
              jobs_.add(
                  input.readMessage(ru.itis.hr.grpc.pb.job.JobOuterClass.Job.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          jobs_ = java.util.Collections.unmodifiableList(jobs_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ru.itis.hr.grpc.pb.job.JobOuterClass.internal_static_JobResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ru.itis.hr.grpc.pb.job.JobOuterClass.internal_static_JobResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ru.itis.hr.grpc.pb.job.JobOuterClass.JobResponse.class, ru.itis.hr.grpc.pb.job.JobOuterClass.JobResponse.Builder.class);
    }

    public static final int JOBS_FIELD_NUMBER = 1;
    private java.util.List<ru.itis.hr.grpc.pb.job.JobOuterClass.Job> jobs_;
    /**
     * <code>repeated .Job jobs = 1;</code>
     */
    @java.lang.Override
    public java.util.List<ru.itis.hr.grpc.pb.job.JobOuterClass.Job> getJobsList() {
      return jobs_;
    }
    /**
     * <code>repeated .Job jobs = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends ru.itis.hr.grpc.pb.job.JobOuterClass.JobOrBuilder> 
        getJobsOrBuilderList() {
      return jobs_;
    }
    /**
     * <code>repeated .Job jobs = 1;</code>
     */
    @java.lang.Override
    public int getJobsCount() {
      return jobs_.size();
    }
    /**
     * <code>repeated .Job jobs = 1;</code>
     */
    @java.lang.Override
    public ru.itis.hr.grpc.pb.job.JobOuterClass.Job getJobs(int index) {
      return jobs_.get(index);
    }
    /**
     * <code>repeated .Job jobs = 1;</code>
     */
    @java.lang.Override
    public ru.itis.hr.grpc.pb.job.JobOuterClass.JobOrBuilder getJobsOrBuilder(
        int index) {
      return jobs_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < jobs_.size(); i++) {
        output.writeMessage(1, jobs_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < jobs_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, jobs_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ru.itis.hr.grpc.pb.job.JobOuterClass.JobResponse)) {
        return super.equals(obj);
      }
      ru.itis.hr.grpc.pb.job.JobOuterClass.JobResponse other = (ru.itis.hr.grpc.pb.job.JobOuterClass.JobResponse) obj;

      if (!getJobsList()
          .equals(other.getJobsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getJobsCount() > 0) {
        hash = (37 * hash) + JOBS_FIELD_NUMBER;
        hash = (53 * hash) + getJobsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ru.itis.hr.grpc.pb.job.JobOuterClass.JobResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.itis.hr.grpc.pb.job.JobOuterClass.JobResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.itis.hr.grpc.pb.job.JobOuterClass.JobResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.itis.hr.grpc.pb.job.JobOuterClass.JobResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.itis.hr.grpc.pb.job.JobOuterClass.JobResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.itis.hr.grpc.pb.job.JobOuterClass.JobResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.itis.hr.grpc.pb.job.JobOuterClass.JobResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ru.itis.hr.grpc.pb.job.JobOuterClass.JobResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ru.itis.hr.grpc.pb.job.JobOuterClass.JobResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ru.itis.hr.grpc.pb.job.JobOuterClass.JobResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ru.itis.hr.grpc.pb.job.JobOuterClass.JobResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ru.itis.hr.grpc.pb.job.JobOuterClass.JobResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ru.itis.hr.grpc.pb.job.JobOuterClass.JobResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code JobResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:JobResponse)
        ru.itis.hr.grpc.pb.job.JobOuterClass.JobResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ru.itis.hr.grpc.pb.job.JobOuterClass.internal_static_JobResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ru.itis.hr.grpc.pb.job.JobOuterClass.internal_static_JobResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ru.itis.hr.grpc.pb.job.JobOuterClass.JobResponse.class, ru.itis.hr.grpc.pb.job.JobOuterClass.JobResponse.Builder.class);
      }

      // Construct using ru.itis.hr.grpc.pb.job.JobOuterClass.JobResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getJobsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (jobsBuilder_ == null) {
          jobs_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          jobsBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ru.itis.hr.grpc.pb.job.JobOuterClass.internal_static_JobResponse_descriptor;
      }

      @java.lang.Override
      public ru.itis.hr.grpc.pb.job.JobOuterClass.JobResponse getDefaultInstanceForType() {
        return ru.itis.hr.grpc.pb.job.JobOuterClass.JobResponse.getDefaultInstance();
      }

      @java.lang.Override
      public ru.itis.hr.grpc.pb.job.JobOuterClass.JobResponse build() {
        ru.itis.hr.grpc.pb.job.JobOuterClass.JobResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ru.itis.hr.grpc.pb.job.JobOuterClass.JobResponse buildPartial() {
        ru.itis.hr.grpc.pb.job.JobOuterClass.JobResponse result = new ru.itis.hr.grpc.pb.job.JobOuterClass.JobResponse(this);
        int from_bitField0_ = bitField0_;
        if (jobsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            jobs_ = java.util.Collections.unmodifiableList(jobs_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.jobs_ = jobs_;
        } else {
          result.jobs_ = jobsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ru.itis.hr.grpc.pb.job.JobOuterClass.JobResponse) {
          return mergeFrom((ru.itis.hr.grpc.pb.job.JobOuterClass.JobResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ru.itis.hr.grpc.pb.job.JobOuterClass.JobResponse other) {
        if (other == ru.itis.hr.grpc.pb.job.JobOuterClass.JobResponse.getDefaultInstance()) return this;
        if (jobsBuilder_ == null) {
          if (!other.jobs_.isEmpty()) {
            if (jobs_.isEmpty()) {
              jobs_ = other.jobs_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureJobsIsMutable();
              jobs_.addAll(other.jobs_);
            }
            onChanged();
          }
        } else {
          if (!other.jobs_.isEmpty()) {
            if (jobsBuilder_.isEmpty()) {
              jobsBuilder_.dispose();
              jobsBuilder_ = null;
              jobs_ = other.jobs_;
              bitField0_ = (bitField0_ & ~0x00000001);
              jobsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getJobsFieldBuilder() : null;
            } else {
              jobsBuilder_.addAllMessages(other.jobs_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ru.itis.hr.grpc.pb.job.JobOuterClass.JobResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ru.itis.hr.grpc.pb.job.JobOuterClass.JobResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<ru.itis.hr.grpc.pb.job.JobOuterClass.Job> jobs_ =
        java.util.Collections.emptyList();
      private void ensureJobsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          jobs_ = new java.util.ArrayList<ru.itis.hr.grpc.pb.job.JobOuterClass.Job>(jobs_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          ru.itis.hr.grpc.pb.job.JobOuterClass.Job, ru.itis.hr.grpc.pb.job.JobOuterClass.Job.Builder, ru.itis.hr.grpc.pb.job.JobOuterClass.JobOrBuilder> jobsBuilder_;

      /**
       * <code>repeated .Job jobs = 1;</code>
       */
      public java.util.List<ru.itis.hr.grpc.pb.job.JobOuterClass.Job> getJobsList() {
        if (jobsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(jobs_);
        } else {
          return jobsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Job jobs = 1;</code>
       */
      public int getJobsCount() {
        if (jobsBuilder_ == null) {
          return jobs_.size();
        } else {
          return jobsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Job jobs = 1;</code>
       */
      public ru.itis.hr.grpc.pb.job.JobOuterClass.Job getJobs(int index) {
        if (jobsBuilder_ == null) {
          return jobs_.get(index);
        } else {
          return jobsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Job jobs = 1;</code>
       */
      public Builder setJobs(
          int index, ru.itis.hr.grpc.pb.job.JobOuterClass.Job value) {
        if (jobsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureJobsIsMutable();
          jobs_.set(index, value);
          onChanged();
        } else {
          jobsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Job jobs = 1;</code>
       */
      public Builder setJobs(
          int index, ru.itis.hr.grpc.pb.job.JobOuterClass.Job.Builder builderForValue) {
        if (jobsBuilder_ == null) {
          ensureJobsIsMutable();
          jobs_.set(index, builderForValue.build());
          onChanged();
        } else {
          jobsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Job jobs = 1;</code>
       */
      public Builder addJobs(ru.itis.hr.grpc.pb.job.JobOuterClass.Job value) {
        if (jobsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureJobsIsMutable();
          jobs_.add(value);
          onChanged();
        } else {
          jobsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Job jobs = 1;</code>
       */
      public Builder addJobs(
          int index, ru.itis.hr.grpc.pb.job.JobOuterClass.Job value) {
        if (jobsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureJobsIsMutable();
          jobs_.add(index, value);
          onChanged();
        } else {
          jobsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Job jobs = 1;</code>
       */
      public Builder addJobs(
          ru.itis.hr.grpc.pb.job.JobOuterClass.Job.Builder builderForValue) {
        if (jobsBuilder_ == null) {
          ensureJobsIsMutable();
          jobs_.add(builderForValue.build());
          onChanged();
        } else {
          jobsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Job jobs = 1;</code>
       */
      public Builder addJobs(
          int index, ru.itis.hr.grpc.pb.job.JobOuterClass.Job.Builder builderForValue) {
        if (jobsBuilder_ == null) {
          ensureJobsIsMutable();
          jobs_.add(index, builderForValue.build());
          onChanged();
        } else {
          jobsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Job jobs = 1;</code>
       */
      public Builder addAllJobs(
          java.lang.Iterable<? extends ru.itis.hr.grpc.pb.job.JobOuterClass.Job> values) {
        if (jobsBuilder_ == null) {
          ensureJobsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, jobs_);
          onChanged();
        } else {
          jobsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Job jobs = 1;</code>
       */
      public Builder clearJobs() {
        if (jobsBuilder_ == null) {
          jobs_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          jobsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Job jobs = 1;</code>
       */
      public Builder removeJobs(int index) {
        if (jobsBuilder_ == null) {
          ensureJobsIsMutable();
          jobs_.remove(index);
          onChanged();
        } else {
          jobsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Job jobs = 1;</code>
       */
      public ru.itis.hr.grpc.pb.job.JobOuterClass.Job.Builder getJobsBuilder(
          int index) {
        return getJobsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Job jobs = 1;</code>
       */
      public ru.itis.hr.grpc.pb.job.JobOuterClass.JobOrBuilder getJobsOrBuilder(
          int index) {
        if (jobsBuilder_ == null) {
          return jobs_.get(index);  } else {
          return jobsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Job jobs = 1;</code>
       */
      public java.util.List<? extends ru.itis.hr.grpc.pb.job.JobOuterClass.JobOrBuilder> 
           getJobsOrBuilderList() {
        if (jobsBuilder_ != null) {
          return jobsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(jobs_);
        }
      }
      /**
       * <code>repeated .Job jobs = 1;</code>
       */
      public ru.itis.hr.grpc.pb.job.JobOuterClass.Job.Builder addJobsBuilder() {
        return getJobsFieldBuilder().addBuilder(
            ru.itis.hr.grpc.pb.job.JobOuterClass.Job.getDefaultInstance());
      }
      /**
       * <code>repeated .Job jobs = 1;</code>
       */
      public ru.itis.hr.grpc.pb.job.JobOuterClass.Job.Builder addJobsBuilder(
          int index) {
        return getJobsFieldBuilder().addBuilder(
            index, ru.itis.hr.grpc.pb.job.JobOuterClass.Job.getDefaultInstance());
      }
      /**
       * <code>repeated .Job jobs = 1;</code>
       */
      public java.util.List<ru.itis.hr.grpc.pb.job.JobOuterClass.Job.Builder> 
           getJobsBuilderList() {
        return getJobsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          ru.itis.hr.grpc.pb.job.JobOuterClass.Job, ru.itis.hr.grpc.pb.job.JobOuterClass.Job.Builder, ru.itis.hr.grpc.pb.job.JobOuterClass.JobOrBuilder> 
          getJobsFieldBuilder() {
        if (jobsBuilder_ == null) {
          jobsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              ru.itis.hr.grpc.pb.job.JobOuterClass.Job, ru.itis.hr.grpc.pb.job.JobOuterClass.Job.Builder, ru.itis.hr.grpc.pb.job.JobOuterClass.JobOrBuilder>(
                  jobs_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          jobs_ = null;
        }
        return jobsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:JobResponse)
    }

    // @@protoc_insertion_point(class_scope:JobResponse)
    private static final ru.itis.hr.grpc.pb.job.JobOuterClass.JobResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ru.itis.hr.grpc.pb.job.JobOuterClass.JobResponse();
    }

    public static ru.itis.hr.grpc.pb.job.JobOuterClass.JobResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<JobResponse>
        PARSER = new com.google.protobuf.AbstractParser<JobResponse>() {
      @java.lang.Override
      public JobResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new JobResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<JobResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<JobResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ru.itis.hr.grpc.pb.job.JobOuterClass.JobResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_JobRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_JobRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Job_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Job_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_JobResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_JobResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tjob.proto\"\032\n\nJobRequest\022\014\n\004page\030\001 \001(\003\"" +
      "Q\n\003Job\022\026\n\016jobDescription\030\001 \001(\t\022\016\n\006salary" +
      "\030\002 \001(\r\022\022\n\nexperience\030\003 \001(\r\022\016\n\006skills\030\004 \003" +
      "(\t\"!\n\013JobResponse\022\022\n\004jobs\030\001 \003(\0132\004.Job23\n" +
      "\nJobService\022%\n\006GetJob\022\013.JobRequest\032\014.Job" +
      "Response\"\000B\030\n\026ru.itis.hr.grpc.pb.jobb\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_JobRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_JobRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_JobRequest_descriptor,
        new java.lang.String[] { "Page", });
    internal_static_Job_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Job_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Job_descriptor,
        new java.lang.String[] { "JobDescription", "Salary", "Experience", "Skills", });
    internal_static_JobResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_JobResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_JobResponse_descriptor,
        new java.lang.String[] { "Jobs", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
